FROM archlinux:base-devel

RUN pacman -Syu --noconfirm && \
    pacman -S stack graphviz curl zip unzip --noconfirm --needed && \
    stack upgrade

##ENV VERSION 1.6.1
ENV MAUDE_URL http://maude.cs.illinois.edu/w/images/5/5d/Maude-2.7.1-linux.zip
## http://maude.cs.illinois.edu/w/images/3/38/Maude-3.1-linux.zip
# maude
RUN set -xe \
    && mkdir -p /dependencies \ 	
    && curl -q -s -S -L --create-dirs -o maude.zip $MAUDE_URL \
    && unzip maude.zip -d /dependencies \
    && mv /dependencies/maude.linux64 /dependencies/maude \
    && chmod -R +x /dependencies \
    && cp -R dependencies/* /usr/local/bin \
    && ln -s /usr/lib/libtinfo.so.6 /usr/lib/libtinfo.so.5

#VOLUME /tamarin-prover

RUN useradd -m tamarin \
    && mkdir /tamarin-prover \
    && chmod 775 /tamarin-prover && chown -R tamarin:tamarin /tamarin-prover
    
USER tamarin

WORKDIR /tamarin-prover

COPY tamarin-prover .

EXPOSE 3001

RUN make default

ENV PATH "/root/.local/bin:${PATH}"
#WORKDIR /home/tamarin/.local/bin    

ENTRYPOINT ["tamarin-prover"]

CMD ["--help"]
