FROM ubuntu:latest

RUN apt-get update \
    && apt-get upgrade -y

ENV TZ=Europe/Kiev

RUN ln -snf /usr/share/zoneinfo/$TZ /etc/localtime && echo $TZ > /etc/timezone

#ENV VERSION 1.6.1
ENV MAUDE_URL http://maude.cs.illinois.edu/w/images/5/5d/Maude-2.7.1-linux.zip
# http://maude.cs.illinois.edu/w/images/3/38/Maude-3.1-linux.zip

# maude
RUN set -xe \
    && apt-get install -y curl zip unzip \ 
    && curl -q -s -S -L --create-dirs -o maude.zip $MAUDE_URL \
    && unzip maude.zip -d /usr/local/bin

# haskell - make
RUN set -xe \  
    && curl -sSL https://get.haskellstack.org/ | sh \
    && stack upgrade \
    && apt-get install -y build-essential \
    && apt-get install -y make 

VOLUME /workspace

COPY . /workspace/

WORKDIR /workspace

# setup
RUN make default

RUN set -xe \
	&& addgroup tamarin \
	&& adduser --disabled-password --gecos '' --ingroup tamarin tamarin \
	&& apt-get install -y graphviz libtinfo5 \
	&& apt-get clean

USER tamarin

EXPOSE 3001

ENTRYPOINT ["tamarin-prover"]

CMD ["interactive", "."]
